
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const services = [
  {
    title: 'Cloud Solutions',
    slug: 'cloud-solutions',
    description: 'Scalable and secure cloud infrastructure to power your applications, ensuring reliability and performance.',
    link: '/services/cloud-solutions',
    fullDescription: 'We provide comprehensive cloud solutions, from infrastructure setup to migration and management. Our services are designed to be scalable, secure, and cost-effective, helping you leverage the full power of the cloud.',
    image: PlaceHolderImages.find((img) => img.id === 'service-1'),
    features: [
      'Cloud infrastructure setup (AWS, Azure, GCP)',
      'Serverless architecture design',
      'Cloud migration and modernization',
      'Containerization with Docker and Kubernetes',
      'Cost optimization and management',
    ],
  },
  {
    title: 'Cyber Security',
    slug: 'cyber-security',
    description: 'Protect your digital assets with our advanced threat detection and prevention services.',
    link: '/services/cyber-security',
    fullDescription: 'Our cybersecurity services offer 360-degree protection for your digital assets. We identify vulnerabilities, protect against threats, and ensure compliance with industry standards.',
    image: PlaceHolderImages.find((img) => img.id === 'service-2'),
    features: [
      'Vulnerability assessment and penetration testing',
      'Managed detection and response (MDR)',
      'Security architecture review',
      'Compliance and governance (ISO 27001, SOC 2)',
      'Employee security training',
    ],
  },
  {
    title: 'AI & Machine Learning',
    slug: 'ai-machine-learning',
    description: 'Leverage the power of AI to unlock insights, automate processes, and drive innovation.',
    link: '/services/ai-machine-learning',
    fullDescription: 'We help you harness the power of Artificial Intelligence and Machine Learning to build intelligent applications, automate processes, and gain a competitive edge.',
    image: PlaceHolderImages.find((img) => img.id === 'service-3'),
    features: [
      'Custom machine learning model development',
      'Natural Language Processing (NLP) solutions',
      'Computer vision and image analysis',
      'Predictive analytics and forecasting',
      'AI-powered automation',
    ],
  },
  {
    title: 'Data Analytics',
    slug: 'data-analytics',
    description: 'Turn your data into actionable intelligence with our comprehensive analytics platforms.',
    link: '/services/data-analytics',
    fullDescription: 'Our data analytics services help you make sense of your data. We build data pipelines, create interactive dashboards, and provide insights to drive business decisions.',
    image: PlaceHolderImages.find((img) => img.id === 'service-4'),
    features: [
      'Data warehousing and ETL pipelines',
      'Business intelligence dashboard development',
      'Real-time data processing and analytics',
      'Big data solutions (Hadoop, Spark)',
      'Data visualization and reporting',
    ],
  },
  {
    title: 'Digital Marketing',
    slug: 'digital-marketing',
    description: 'Expand your reach and engage your audience with data-driven marketing strategies.',
    link: '/services/digital-marketing',
    fullDescription: 'Our digital marketing services are designed to grow your online presence. From SEO to social media, we create and execute strategies that deliver results.',
    image: PlaceHolderImages.find((img) => img.id === 'service-5'),
    features: [
      'Search Engine Optimization (SEO)',
      'Pay-Per-Click (PPC) advertising',
      'Social media marketing and management',
      'Content marketing and strategy',
      'Email marketing and automation',
    ],
  },
  {
    title: 'UX/UI Design',
    slug: 'ux-ui-design',
    description: 'Create beautiful, intuitive, and user-centric digital experiences that delight users.',
    link: '/services/ux-ui-design',
    fullDescription: 'We design user-centric digital products that are not only visually appealing but also easy to use. Our design process is collaborative, iterative, and focused on your business goals.',
    image: PlaceHolderImages.find((img) => img.id === 'service-6'),
    features: [
      'User research and persona development',
      'Wireframing and prototyping',
      'User interface (UI) design',
      'User experience (UX) strategy',
      'Design system creation and management',
    ],
  },
];
